### ISSUE TITLE
Fix singleton problem

### ISSUE THREAD

**Issue by baldore** [andrscrrn/pizza-guy#49]

**Comment by baldore** [comment]
Ok, I'm working on this but, since there's no more singleton, I need to remove a lot of tests, like this one:

```javascript
it('should throw an error for non-strings', function() {
  expect(() => pizzaGuy.onAddress(null)).toThrow(/The address must be a string/);
});
```

Why? because the whole API will work different, so the only for to create a instance is with new or with  the static method deliver, that looks like this:

```javascript
function PizzaGuy() {
  this.fileList = [];
}

PizzaGuy.deliver = function(fileList) {
  const instance = new PizzaGuy();
  instance.deliver(fileList);

  return instance;
};
```

Take a look and let me know what do you think.

**Comment by andresdavid90** [comment]
But we can still check that these functions are checking that the value being passed is the right one, right? And having that in mind, it would be a slightly different test but basically the same one. Thoughts?

**Comment by baldore** [comment]
They are basically the same, but we need to use `new PizzaGuy()` in those tests to really check that the initial instance is the same one returned by each method.

**Comment by andresdavid90** [comment]
Yeah, exactly.
