### ISSUE TITLE
Provide HTTP authentication

### ISSUE THREAD

**Issue by glrodasz** [andrscrrn/pizza-guy#58]
Hi, guys I was thinking that it will possible that someone requires downloading files from a server that requires authentication.

I see that the `request` package have the setup for this so we should provide an object configuration for that. 

What do you think?

**Comment by andresdavid90** [comment]
I think it makes sense. Any real example? It would be useful to test it against some real service.

**Comment by entrptaher** [comment]
Well, this says the download succeed, but it doesn't. A basic auth page. 

```js
var pizzaGuy = require('pizza-guy');
const files = [
  'https://httpbin.org/basic-auth/user/passwd'
];
pizzaGuy
  .deliver(files)
  .onAddress('./downloads')
  .onSuccess((info) => {
    console.log(`${info.fileName} succeed!`);
  })
  .onError((info) => {
    console.log(`${info.fileName} failed`);
  })
  .start();
```

**Comment by andrscrrn** [comment]
I think that for those cases we could do two things.

1. For now the easiest thing would be to identify if a provided url is using any kind of authentication and let the user know that pizza-guy wouldn't download anything from that specific url.
2. The second thing that we can do, is actually implement this feature.

Both are actually a good idea, and we can probably work on both.

@entrptaher would you like to help on this? 🙂

**Comment by entrptaher** [comment]
To determine if the url is using auth, you can rely on http status codes.
A header response with status code 200 means the connection is okay.
And, 401 means the request requires user authentication.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
